#pragma once

#include <QtCore/qglobal.h>

#if defined(HE_BUILD_CONTROL_LIB)
#  define HE_CONTROL_EXPORT Q_DECL_EXPORT
#else
#  define HE_CONTROL_EXPORT Q_DECL_IMPORT
#endif

#define HE_CONTROL_NAMESPACE HeControl

#ifdef HE_CONTROL_NAMESPACE
#  define HE_CONTROL_BEGIN_NAMESPACE namespace HE_CONTROL_NAMESPACE {
#  define HE_CONTROL_END_NAMESPACE }
#  define HE_CONTROL_USE_NAMESPACE using namespace HE_CONTROL_NAMESPACE;
#else
#  define HE_CONTROL_BEGIN_NAMESPACE
#  define HE_CONTROL_END_NAMESPACE
#  define HE_CONTROL_USE_NAMESPACE
#endif

HE_CONTROL_BEGIN_NAMESPACE
HE_CONTROL_END_NAMESPACE
