#pragma once

#include <QtCore/qglobal.h>

#if defined(HE_BUILD_CONTROLLER_LIB)
#  define HE_CONTROLLER_EXPORT Q_DECL_EXPORT
#else
#  define HE_CONTROLLER_EXPORT Q_DECL_IMPORT
#endif

//#define HE_CONTROLLER_NAMESPACE HeController

#ifdef HE_CONTROLLER_NAMESPACE
#  define HE_CONTROLLER_BEGIN_NAMESPACE namespace HE_CONTROLLER_NAMESPACE {
#  define HE_CONTROLLER_END_NAMESPACE }
#  define HE_CONTROLLER_USE_NAMESPACE using namespace HE_CONTROLLER_NAMESPACE;
#else
#  define HE_CONTROLLER_BEGIN_NAMESPACE
#  define HE_CONTROLLER_END_NAMESPACE
#  define HE_CONTROLLER_USE_NAMESPACE
#endif

HE_CONTROLLER_BEGIN_NAMESPACE
HE_CONTROLLER_END_NAMESPACE
