#ifndef HTESTDATAFACTORY_P_H
#define HTESTDATAFACTORY_P_H

#include "HTestDataFactory.h"

HE_CONTROLLER_BEGIN_NAMESPACE

class HTestDataFactoryPrivate
{
};

HE_CONTROLLER_END_NAMESPACE

#endif // HTESTDATAFACTORY_P_H
