#ifndef HEREFERENCE_GLOBAL_H
#define HEREFERENCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HE_BUILD_REFERENCE_LIB)
#  define HE_REFERENCE_EXPORT Q_DECL_EXPORT
#else
#  define HE_REFERENCE_EXPORT Q_DECL_IMPORT
#endif

#define HE_REFERENCE_NAMESPACE HeReferenced

#ifdef HE_REFERENCE_NAMESPACE
#  define HE_REFERENCE_BEGIN_NAMESPACE namespace HE_REFERENCE_NAMESPACE {
#  define HE_REFERENCE_END_NAMESPACE }
#  define HE_REFERENCE_USE_NAMESPACE using namespace HE_REFERENCE_NAMESPACE;
#else
#  define HE_REFERENCE_BEGIN_NAMESPACE
#  define HE_REFERENCE_END_NAMESPACE
#  define HE_REFERENCE_USE_NAMESPACE
#endif

HE_REFERENCE_BEGIN_NAMESPACE
HE_REFERENCE_END_NAMESPACE

#endif // HEREFERENCE_GLOBAL_H
