#ifndef HALGORITHMGLOBAL_H
#define HALGORITHMGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HE_BUILD_ALGORITHM_LIB)
#  define HE_ALGORITHM_EXPORT Q_DECL_EXPORT
#else
#  define HE_ALGORITHM_EXPORT Q_DECL_IMPORT
#endif

#define HE_ALGORITHM_NAMESPACE HeAlgorithm

#ifdef HE_ALGORITHM_NAMESPACE
#  define HE_ALGORITHM_BEGIN_NAMESPACE namespace HE_ALGORITHM_NAMESPACE {
#  define HE_ALGORITHM_END_NAMESPACE }
#  define HE_ALGORITHM_USE_NAMESPACE using namespace HE_ALGORITHM_NAMESPACE;
#else
#  define HE_ALGORITHM_BEGIN_NAMESPACE
#  define HE_ALGORITHM_END_NAMESPACE
#  define HE_ALGORITHM_USE_NAMESPACE
#endif

HE_ALGORITHM_BEGIN_NAMESPACE
HE_ALGORITHM_END_NAMESPACE

#endif // HALGORITHMGLOBAL_H
