#ifndef HCOMMUNICATEFACTORY_P_H
#define HCOMMUNICATEFACTORY_P_H

#include "HCommunicateFactory.h"

HE_COMMUNICATE_BEGIN_NAMESPACE

class HCommunicateFactoryPrivate
{
};

HE_COMMUNICATE_END_NAMESPACE

#endif // HCOMMUNICATEFACTORY_P_H
