#pragma once

#include <QtCore/qglobal.h>

#if defined(HE_BUILD_COMMUNICATE_LIB)
#  define HE_COMMUNICATE_EXPORT Q_DECL_EXPORT
#else
#  define HE_COMMUNICATE_EXPORT Q_DECL_IMPORT
#endif

#define HE_COMMUNICATE_NAMESPACE HeCommunicate

#ifdef HE_COMMUNICATE_NAMESPACE
#  define HE_COMMUNICATE_BEGIN_NAMESPACE namespace HE_COMMUNICATE_NAMESPACE {
#  define HE_COMMUNICATE_END_NAMESPACE }
#  define HE_COMMUNICATE_USE_NAMESPACE using namespace HE_COMMUNICATE_NAMESPACE;
#else
#  define HE_COMMUNICATE_BEGIN_NAMESPACE
#  define HE_COMMUNICATE_END_NAMESPACE
#  define HE_COMMUNICATE_USE_NAMESPACE
#endif

HE_COMMUNICATE_BEGIN_NAMESPACE
HE_COMMUNICATE_END_NAMESPACE
