#ifndef HPROTOCOLCOLLECTION_P_H
#define HPROTOCOLCOLLECTION_P_H

#include "HProtocolCollection.h"

HE_COMMUNICATE_BEGIN_NAMESPACE

class HProtocolCollectionPrivate
{
};

HE_COMMUNICATE_END_NAMESPACE

#endif // HPROTOCOLCOLLECTION_P_H
